"""add detailed_notes flashcards tldr to note_content

Revision ID: 7e4920c4dc7b
Revises: 80ba33ee8ffa
Create Date: 2026-06-21 00:19:18.579799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e4920c4dc7b'
down_revision: Union[str, Sequence[str], None] = '80ba33ee8ffa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note_content', sa.Column('detailed_notes', sa.JSON(), nullable=True))
    op.add_column('note_content', sa.Column('flashcards', sa.JSON(), nullable=True))
    op.add_column('note_content', sa.Column('tldr', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note_content', 'tldr')
    op.drop_column('note_content', 'flashcards')
    op.drop_column('note_content', 'detailed_notes')
    # ### end Alembic commands ###
